# Welcome to the Makefile tutorial!

# This is what a simple "rule" looks like-
# target: dependecy(ies)
#         recipe(s)
# e.g.
# hello: hello.c
#       # "recipe" (command) to compile hello.c
#        gcc hello.c

# 2.1
# Write a rule to compile this file sample.c

# 2.2
# Modify the rule so that the command "make myrule" compiles this same file sample.c and generates a binary named "sample.bin"
