# Welcome to the Makefile tutorial!

# This is what a simple "rule" looks like-
# target: dependecy(ies)
#         recipe(s)
# e.g.
# hello: hello.c
#       # "recipe" (command) to compile hello.c
#        gcc hello.c

# task1-
# Write a rule to compile this file sample.c

# task2-
# Modify the same rule so that the generated binary is named "task2.bin"
