# Welcome to the Makefile tutorial

# This is what a simple "rule" looks like-
# target: dependecy(ies)
#         recipe(s)
# e.g.
# hello: hello.c
#       # "recipe" (command) to compile hello.c
#        gcc hello.c

# task1-
# Write a rule to compile this file try.c
# run test_task1.py

# task2-
# Modify the same rule so that the generated binary is named "task2.bin"
# run test_task2.py
