# Welcome to the Makefile tutorial

# This is what a simple "rule" looks like-
# target: dependecy(ies)
#         recipe(s)
# e.g.
# hello: hello.c
#       # "recipe" (command) to compile hello.c
#        gcc hello.c
